import { User, Complaint, DashboardStats } from './types';

// Mock users
export const mockUsers: Record<string, User> = {
  citizen1: {
    id: 'citizen1',
    email: 'user@gmail.kz',
    name: 'Ерлан Сейтов',
    role: 'citizen',
    avatar: '👤',
    district: 'Alatau',
  },
  citizen2: {
    id: 'citizen2',
    email: 'citizen@gmail.kz',
    name: 'Айнур Қалиева',
    role: 'citizen',
    avatar: '👩',
    district: 'Bostandyk',
  },
  gov1: {
    id: 'gov1',
    email: 'officer@gov.kz',
    name: 'Дмитрий Петров',
    role: 'government',
    avatar: '👨‍💼',
    department: 'Экология',
  },
  gov2: {
    id: 'gov2',
    email: 'manager@gov.kz',
    name: 'Гульнара Ибраимова',
    role: 'government',
    avatar: '👩‍💼',
    department: 'ЖКХ',
  },
};

// Mock complaints
export const mockComplaints: Complaint[] = [
  {
    id: 'complaint1',
    title: 'Засоренный парк в районе Ауэзова',
    description: 'Парк на улице Ауэзова заполнен мусором. Требуется срочная уборка и озеленение.',
    category: 'ecology',
    status: 'resolved',
    urgency: 'high',
    createdAt: '2026-03-25T10:30:00Z',
    updatedAt: '2026-04-02T14:20:00Z',
    createdBy: mockUsers.citizen1,
    assignedTo: mockUsers.gov1,
    location: {
      lat: 43.2381,
      lng: 76.9453,
      address: 'Парк Ауэзова, Алматы',
      district: 'Auezov',
    },
    images: [],
    comments: [
      {
        id: 'comment1',
        text: 'Начали уборку территории. Завершим в течение 3 дней.',
        author: mockUsers.gov1,
        createdAt: '2026-03-26T09:00:00Z',
      },
      {
        id: 'comment2',
        text: 'Уборка завершена. Спасибо за оперативность!',
        author: mockUsers.citizen1,
        createdAt: '2026-04-02T14:20:00Z',
      },
    ],
    rating: 5,
  },
  {
    id: 'complaint2',
    title: 'Поврежденная крыша в доме на ул. Толе Би',
    description: 'Крыша дома протекает. Нужен срочный ремонт перед сезоном дождей.',
    category: 'housing',
    status: 'in_progress',
    urgency: 'critical',
    createdAt: '2026-04-01T08:15:00Z',
    updatedAt: '2026-04-03T11:30:00Z',
    createdBy: mockUsers.citizen2,
    assignedTo: mockUsers.gov2,
    location: {
      lat: 43.2350,
      lng: 76.9380,
      address: 'ул. Толе Би, 123, Алматы',
      district: 'Bostandyk',
    },
    images: [],
    comments: [
      {
        id: 'comment3',
        text: 'Принято в работу. Направляем бригаду осмотра на завтра.',
        author: mockUsers.gov2,
        createdAt: '2026-04-01T16:00:00Z',
      },
    ],
  },
  {
    id: 'complaint3',
    title: 'Отсутствие уличного освещения на ул. Сейфуллина',
    description: 'На улице Сейфуллина в районе дома 456 нет уличного освещения. Опасно по ночам.',
    category: 'akimat',
    status: 'pending_approval',
    urgency: 'medium',
    createdAt: '2026-04-02T14:45:00Z',
    updatedAt: '2026-04-02T16:20:00Z',
    createdBy: mockUsers.citizen1,
    location: {
      lat: 43.2420,
      lng: 76.9510,
      address: 'ул. Сейфуллина, 456, Алматы',
      district: 'Turksib',
    },
    images: [],
    comments: [],
  },
  {
    id: 'complaint4',
    title: 'Засохшие деревья в сквере Панфилова',
    description: 'Большинство деревьев в сквере засохли. Требуется замена и новая посадка.',
    category: 'ecology',
    status: 'new',
    urgency: 'medium',
    createdAt: '2026-04-03T09:20:00Z',
    updatedAt: '2026-04-03T09:20:00Z',
    createdBy: mockUsers.citizen2,
    location: {
      lat: 43.2290,
      lng: 76.9420,
      address: 'Сквер Панфилова, Алматы',
      district: 'Almaly',
    },
    images: [],
    comments: [],
  },
  {
    id: 'complaint5',
    title: 'Неработающий лифт в доме на ул. Абая',
    description: 'Лифт в подъезде 2 не работает уже неделю. Жители верхних этажей испытывают трудности.',
    category: 'housing',
    status: 'in_progress',
    urgency: 'high',
    createdAt: '2026-03-28T11:00:00Z',
    updatedAt: '2026-04-02T10:15:00Z',
    createdBy: mockUsers.citizen1,
    assignedTo: mockUsers.gov2,
    location: {
      lat: 43.2310,
      lng: 76.9390,
      address: 'ул. Абая, 789, Алматы',
      district: 'Medeu',
    },
    images: [],
    comments: [
      {
        id: 'comment4',
        text: 'Техник выезжает на осмотр. Ожидаем диагностику в течение 24 часов.',
        author: mockUsers.gov2,
        createdAt: '2026-03-29T08:30:00Z',
      },
    ],
  },
  {
    id: 'complaint6',
    title: 'Загрязнение воздуха на ул. Сатпаева',
    description: 'Постоянный дым и неприятный запах от промышленного объекта. Влияет на здоровье жителей.',
    category: 'ecology',
    status: 'new',
    urgency: 'critical',
    createdAt: '2026-04-03T07:30:00Z',
    updatedAt: '2026-04-03T07:30:00Z',
    createdBy: mockUsers.citizen2,
    location: {
      lat: 43.2270,
      lng: 76.9470,
      address: 'ул. Сатпаева, Алматы',
      district: 'Saryarka',
    },
    images: [],
    comments: [],
    isDuplicate: true,
    duplicateOf: 'complaint7',
  },
  {
    id: 'complaint7',
    title: 'Загрязнение воздуха в районе Сатпаева',
    description: 'Экологическая проблема: выбросы от промышленного предприятия загрязняют воздух.',
    category: 'ecology',
    status: 'in_progress',
    urgency: 'critical',
    createdAt: '2026-04-02T06:00:00Z',
    updatedAt: '2026-04-03T08:00:00Z',
    createdBy: mockUsers.citizen1,
    assignedTo: mockUsers.gov1,
    location: {
      lat: 43.2275,
      lng: 76.9475,
      address: 'ул. Сатпаева, Алматы',
      district: 'Saryarka',
    },
    images: [],
    comments: [
      {
        id: 'comment5',
        text: 'Направлена инспекционная группа для проверки соответствия нормам выбросов.',
        author: mockUsers.gov1,
        createdAt: '2026-04-02T14:00:00Z',
      },
    ],
  },
];

// Mock dashboard stats
export const mockDashboardStats: DashboardStats = {
  totalComplaints: 247,
  newComplaints: 34,
  inProgressComplaints: 89,
  resolvedComplaints: 124,
  averageResolutionTime: 8.5,
  satisfactionRate: 78,
  complaintsByCategory: {
    ecology: 98,
    housing: 102,
    akimat: 47,
    transport: 34,
  },
  complaintsByDistrict: {
    Alatau: 32,
    Auezov: 28,
    Bostandyk: 45,
    Turksib: 38,
    Almaly: 31,
    Medeu: 42,
    Chimkent: 25,
    Saryarka: 6,
  },
  complaintsByStatus: {
    new: 34,
    pending_approval: 28,
    in_progress: 89,
    resolved: 96,
  },
};
